Module1 task1
htmlacademy-javascript/2001021-kekstagram-28 pull request #1
Opened 2023-02-16 12:00 UTC by edmondev80

2023-02-16 13:15 UTC, o-bender commented on Readme.md
> +- Наставник: Павел
Заполни, пожалуйста, по примеру с полем "Студент".

2023-02-16 14:19 UTC, edmondev80 commented
Заполнил!

> 16 февр. 2023 г., в 16:15, Pavel Lukin ***@***.***> написал(а):
> 
> 
> @o-bender commented on this pull request.
> 
> In Readme.md <https://github.com/htmlacademy-javascript/2001021-kekstagram-28/pull/1#discussion_r1108458091>:
> 
> > @@ -1,7 +1,7 @@
>  # Личный проект «Кекстаграм»
>  
> -* Студент: [Эдуард Османов](https://up.htmlacademy.ru/javascript/28/user/2001021).
> -* Наставник: `Неизвестно`.
> +- Студент: [Эдуард Османов](https://up.htmlacademy.ru/javascript/28/user/2001021).
> +- Наставник: Павел
> Заполни, пожалуйста, по примеру с полем "Студент".
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/htmlacademy-javascript/2001021-kekstagram-28/pull/1#pullrequestreview-1301414584>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AMSP33YI5HXWO7CGRI23UGTWXYR67ANCNFSM6AAAAAAU6CTTZQ>.
> You are receiving this because you authored the thread.
>

2023-02-17 09:42 UTC, o-bender requested changes

2023-02-17 09:42 UTC, o-bender commented on Readme.md
> +- Наставник: [Павел Лукин]
Формат файла md это не тоже самое что txt. MD это markdown. И он имеет, хоть и не большой, но набор требований. Ссылки должны иметь формат `[Текст](URL)`. Пробелы и переносы между символами ]( не допустимы.
![image](https://user-images.githubusercontent.com/6534704/219609390-4f6257eb-1574-43b6-ac99-02d14558f8e1.png)

2023-02-17 10:14 UTC, merged